
export { About } from "shared/assets/icons/svg/About"
export { Calendar } from "shared/assets/icons/svg/Calendar"
export { Profile } from "shared/assets/icons/svg/Profile"
export { Article } from "shared/assets/icons/svg/Article"
export { Done } from "shared/assets/icons/svg/Done"
export { Eye } from "shared/assets/icons/svg/Eye"
export { Main } from "shared/assets/icons/svg/Main"
export { ThemeOrange } from "shared/assets/icons/svg/ThemeOrange"
export { ThemeDark } from "shared/assets/icons/svg/ThemeDark"
export { ThemeLight } from "shared/assets/icons/svg/ThemeLight"
export { Tiles } from "shared/assets/icons/svg/Tiles"
export { List } from "shared/assets/icons/svg/List"
export { OrderAsc } from "shared/assets/icons/svg/OrderAsc"
export { OrderDesc } from "shared/assets/icons/svg/OrderDesc"
export { Filter } from "shared/assets/icons/svg/Filter"